apiVersion: v2
description: aloha is an open source threaded team chat that helps teams stay productive and focused.
name: aloha
type: application
icon: https://raw.githubusercontent.com/aloha/aloha/main/static/images/logo/aloha-icon-square.svg
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.4.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "5.6-0"
dependencies:
  - name: memcached
    repository: https://charts.bitnami.com/bitnami
    tags:
      - memcached
    version: 6.0.16
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    tags:
      - rabbitmq
    version: 8.32.0
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
    version: 16.8.7
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
    # Note: values.yaml overwrites posgresql image to aloha/aloha-postgresql:14
    version: 11.1.22

sources:
  - https://github.com/aloha/aloha
  - https://github.com/aloha/docker-aloha
  - https://hub.docker.com/r/aloha/docker-aloha
