apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aloha.fullname" . }}
  labels:
    {{- include "aloha.labels" . | nindent 4 }}
  {{- if .Values.statefulSetLabels }}
    {{- toYaml .Values.statefulSetLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.statefulSetAnnotations }}
  annotations:
    {{- toYaml .Values.statefulSetAnnotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "aloha.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "aloha.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aloha.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aloha.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: {{ include "aloha.fullname" . }}-persistent-storage
              mountPath: /data
            - name: {{ include "aloha.fullname" . }}-post-setup-scripts
              mountPath: /data/post-setup.d
          env:
            {{ include "aloha.env" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
              - name: Host
                value: {{ .Values.aloha.environment.SETTING_EXTERNAL_HOST | quote }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
              - name: Host
                value: {{ .Values.aloha.environment.SETTING_EXTERNAL_HOST | quote }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}
      volumes:
        - name: {{ include "aloha.fullname" . }}-persistent-storage
          persistentVolumeClaim:
            claimName: {{ if .Values.aloha.persistence.existingClaim }}{{ .Values.aloha.persistence.existingClaim }}{{- else }}{{ template "aloha.fullname" . }}-data{{- end }}
        - name: {{ include "aloha.fullname" . }}-post-setup-scripts
          configMap:
            name: {{ include "aloha.fullname" . }}-post-setup-scripts
            defaultMode: 0750
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
