apiVersion: v1
kind: Service
metadata:
  name: aloha
  labels:
    app: aloha
spec:
  selector:
    app: aloha
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
