apiVersion: v1
kind: ReplicationController
metadata:
  name: aloha-1
  labels:
    version: 1.8.1-0
    app: aloha
spec:
  replicas: 1
  selector:
    version: 1.8.1-0
    app: aloha
  template:
    metadata:
      labels:
        version: 1.8.1-0
        app: aloha
    spec:
      containers:
        - name: redis
          image: redis:alpine
          command:
            - "sh"
            - "-euc"
            - |
              echo "requirepass '$$REDIS_PASSWORD'" > /etc/redis.conf
              exec redis-server /etc/redis.conf
          env:
            - name: REDIS_PASSWORD
              value: "REPLACE_WITH_SECURE_REDIS_PASSWORD"
          resources:
            limits:
              cpu: 50m
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /var/lib/redis
        - name: memcached
          image: memcached:alpine
          command:
            - "sh"
            - "-euc"
            - |
              echo 'mech_list: plain' > "$$SASL_CONF_PATH"
              echo "aloha@$$HOSTNAME:$$MEMCACHED_PASSWORD" > "$$MEMCACHED_SASL_PWDB"
              echo "aloha@localhost:$$MEMCACHED_PASSWORD" >> "$$MEMCACHED_SASL_PWDB"
              exec memcached -S
          env:
            - name: SASL_CONF_PATH
              value: "/home/memcache/memcached.conf"
            - name: MEMCACHED_SASL_PWDB
              value: "/home/memcache/memcached-sasl-db"
            - name: MEMCACHED_PASSWORD
              value: "REPLACE_WITH_SECURE_MEMCACHED_PASSWORD"
          resources:
            limits:
              cpu: 75m
              memory: 768Mi
        - name: rabbitmq
          image: rabbitmq:3.7.7
          resources:
            limits:
              cpu: 75m
              memory: 768Mi
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "aloha"
            - name: RABBITMQ_DEFAULT_PASS
              value: "REPLACE_WITH_SECURE_RABBITMQ_PASSWORD"
          volumeMounts:
            - name: rabbitmq-persistent-storage
              mountPath: /var/lib/rabbitmq
        - name: postgresql
          image: aloha/aloha-postgresql
          resources:
            limits:
              cpu: 80m
              memory: 768Mi
          env:
            - name: POSTGRES_DB
              value: aloha
            - name: POSTGRES_USER
              value: aloha
            - name: POSTGRES_PASSWORD
              value: REPLACE_WITH_SECURE_POSTGRES_PASSWORD
          volumeMounts:
            - name: postgresql-persistent-storage
              mountPath: /var/lib/postgresql
        - name: aloha
          image: aloha/docker-aloha:5.6-0
          resources:
            limits:
              cpu: 100m
              memory: 3584Mi
          env:
            # Please take a look at the environment variables in docker-compose.yml for all required env variables!
            - name: DB_HOST
              value: "localhost"
            - name: MEMCACHED_HOST
              value: "localhost"
            - name: REDIS_HOST
              value: "localhost"
            - name: RABBITMQ_HOST
              value: "localhost"
            - name: aloha_AUTH_BACKENDS
              value: "EmailAuthBackend"
            - name: SECRETS_email_password
              value: "123456789"
            - name: SETTING_EXTERNAL_HOST
              value: "localhost"
            - name: SETTING_aloha_ADMINISTRATOR
              value: "admin@example.com"
            - name: SETTING_EMAIL_HOST
              value: "" # E.g. 'smtp.example.com'
            - name: SETTING_EMAIL_HOST_USER
              value: "noreply@example.com"
            - name: aloha_USER_EMAIL
              value: "example@example.com"
            - name: aloha_USER_DOMAIN
              value: "example.com"
            - name: aloha_USER_PASS
              value: "123456789"
            - name: SECRETS_secret_key
              value: "REPLCAE_WITH_SECURE_SECRET_KEY"
            # These should match the passwords configured above
            - name: SECRETS_postgres_password
              value: "REPLACE_WITH_SECURE_POSTGRES_PASSWORD"
            - name: SECRETS_memcached_password
              value: "REPLACE_WITH_SECURE_MEMCACHED_PASSWORD"
            - name: SECRETS_rabbitmq_password
              value: "REPLACE_WITH_SECURE_RABBITMQ_PASSWORD"
            - name: SECRETS_redis_password
              value: "REPLACE_WITH_SECURE_REDIS_PASSWORD"
            - name: SSL_CERTIFICATE_GENERATION
              value: "self-signed"
          # Uncomment this when configuring the mobile push notifications service
          # - name: SETTING_PUSH_NOTIFICATION_BOUNCER_URL
          #   value: 'https://push.alohachat.com'
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          volumeMounts:
            - name: aloha-persistent-storage
              mountPath: /data
      #        livenessProbe:
      #          httpGet:
      #            path: /login
      #            port: 443
      #            scheme: HTTP
      #          initialDelaySeconds: 120
      #          timeoutSeconds: 12
      volumes:
        - name: redis-persistent-storage
          hostPath:
            path: /opt/docker/aloha/redis
        - name: rabbitmq-persistent-storage
          hostPath:
            path: /opt/docker/aloha/rabbitmq
        - name: postgresql-persistent-storage
          hostPath:
            path: /opt/docker/aloha/postgresql
        - name: aloha-persistent-storage
          hostPath:
            path: /opt/docker/aloha/aloha
